# Generated by Django 4.0.3 on 2022-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='database_update_time',
            fields=[
                ('db_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('update_time', models.DateField()),
            ],
            options={
                'db_table': 'update_time',
            },
        ),
        migrations.CreateModel(
            name='example_output',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('language', models.CharField(max_length=8)),
                ('pos_sentiment', models.FloatField()),
                ('neg_sentiment', models.FloatField()),
                ('neu_sentiment', models.FloatField()),
                ('compound_sentiment', models.FloatField()),
                ('tweet_time', models.DateTimeField()),
                ('region_full', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'example_output',
            },
        ),
    ]
