# Generated by Django 4.0.3 on 2022-05-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_api', '0003_example_agg'),
    ]

    operations = [
        migrations.CreateModel(
            name='aggmap',
            fields=[
                ('region_code', models.AutoField(primary_key=True, serialize=False)),
                ('crime_rate', models.FloatField()),
                ('sent_score', models.FloatField()),
                ('no_offensive', models.IntegerField()),
                ('region_full', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'aggmap',
            },
        ),
        migrations.AlterField(
            model_name='example_agg',
            name='region_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
