# Generated by Django 4.0.3 on 2022-05-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_api', '0004_aggmap_alter_example_agg_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggmap',
            name='region_code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
