# Generated by Django 4.0.3 on 2022-05-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_api', '0005_alter_aggmap_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggmap',
            name='region_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
