# Generated by Django 4.0.3 on 2022-05-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_api', '0006_alter_aggmap_region_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainsuburb',
            fields=[
                ('region_code', models.AutoField(primary_key=True, serialize=False)),
                ('crime_rate', models.FloatField()),
                ('sent_score', models.FloatField()),
                ('no_offensive', models.IntegerField()),
                ('region_full', models.CharField(max_length=250)),
                ('offensive_by_hour', models.JSONField()),
                ('word_freq', models.JSONField()),
                ('word_freq_neg', models.JSONField()),
            ],
            options={
                'db_table': 'main_suburb',
            },
        ),
    ]
