# Generated by Django 4.0.3 on 2022-05-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_api', '0008_aggmap_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggmap_new',
            name='fav_food',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
